name: Create custom file
on: push

jobs:
  run:
    name: Create custom file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Create file
        run: |
          echo "Hello World" > build/helloWorld.txt

      - name: Commit changes
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Pramod AJ
          author_email: avj2352@gmail.com
          message: 'Testing commit'
          add: '*.txt'
